### ISSUE TITLE
0x0000000

### ISSUE THREAD

**Issue by Spotifydavid171** [zer0condition/ReverseKit#1]
Any idea why there is some threads with actual values while I load the program but once it's loaded, it only loads 0x0000 and there is nothing in imports

**Comment by zer0condition** [comment]
Can you provide some more information? The target process for example

**Comment by Spotifydavid171** [comment]
Can you give me your discord maybe, I can show you..

**Comment by zer0condition** [comment]
ZeroCondtition#8490

**Comment by Spotifydavid171** [comment]
Does not work

**Comment by zer0condition** [comment]
ZeroCondition#8430 my bad
